[package]
name = "mtree"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
smallvec = "0.6"
log = "0.4"
newtype_array = "0.1"
